<?php

/**
 * @file
 * Contains pw.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Template\Attribute;
/**
 * Implements hook_help().
 */
function pw_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pw module.
    case 'help.page.pw':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides base paragraph features.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pw_theme($existing, $type, $theme, $path) {
  return [
    'field__field_pw_title' => [
      'base hook' => 'field',
    ],
    'field__field_pw_subtitle' => [
      'base hook' => 'field',
    ],
  ];
}


/**
 * Implements hook_preprocess_HOOK().
 */
function pw_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();
  $paragraph_id = 'paragraph-' . $bundle .'-'. $paragraph->id();
  $wrapper_attributes = [
    'id' => $paragraph_id,
    'class' => [
      'wrapper-' . $bundle,
    ],
  ];
  $paragraph_attributes = [
    'data-id' => $paragraph_id,
  ];
  $variables['wrapper_attributes'] = new Attribute($wrapper_attributes);
  $variables['paragraph_attributes'] = new Attribute($paragraph_attributes);

}

